
/:
  controller: main
  action: home

/media:
  controller: admin
  action: media

/plugin:
  controller: admin
  action: plugin

/pages:
  controller: admin
  action: pages_settings

/articles:
  controller: admin
  action: articles

/categories:
  controller: admin
  action: categorie

/contact:
  controller: main
  action: contact

/login:
  controller: user
  action: login

/register:
  controller: user
  action: register

/forget:
  controller: user
  action: pwdforget

/logout:
  controller: user
  action: logout


