


/contact:
  controller: main
  action: contact

/login:
  controller: user
  action: login

/media:
  controller: admin
  action: media

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/forget:
  controller: user
  action: pwdforget

/:
  controller: main
  action: home

