
/:
  controller: main
  action: home

/media:
  controller: admin
  action: media

/plugin:
  controller: admin
  action: plugin
  
/pages:
  controller: page
  action: pages_settings

/articles:
  controller: article
  action: articles

/user_settings:
  controller: admin
  action: user_settings


# /categories:
#   controller: admin
#   action: categorie

/contact:
  controller: main
  action: contact

/login:
  controller: user
  action: login

/register:
  controller: user
  action: register

/addArticle:
  controller: article
  action: addArticle

/addPage:
  controller: page
  action: addPage

/forget:
  controller: user
  action: pwdforget

/veryfieduser:
  controller: user
  action: verificated
  
/logout:
  controller: user
  action: logout

/test:
  controller: admin
  action: builder
  
/dashboard:
  controller: main
  action: home


  
/accountActivated:
  controller: user
  action: verificated

# /installer:
#   controller: installer
#   action: install

# /about:
#   controller: about
#   action: aboutUs

/apparence:
  controller: admin
  action: tplsettings


/Seconde_Page: 
 controller: front 
 action: Seconde_Page 
/Accueuil: 
 controller: front 
 action: Accueuil 
/Nous_contacter: 
 controller: front 
 action: Nous_contacter 
/Nouvelle_Page: 
 controller: front 
 action: Nouvelle_Page 
/Ma_belle_Page: 
 controller: front 
 action: Ma_belle_Page 
/Accueuil: 
 controller: front 
 action: Accueuil 
/Newsletter: 
 controller: front 
 action: Newsletter 
/test: 
 controller: front 
 action: test 
